fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
      ref: 4.11.0
    vcsrepo:
      repo: puppetlabs/vcsrepo
      ref: 1.3.2
    ruby:
      repo: puppetlabs/ruby
      ref: 0.4.0
  symlinks:
    reaktor: "#{source_dir}"
